### ISSUE TITLE
Lock push to database

### ISSUE THREAD

**Issue by iDuuck** [welaika/wordmove#205] opened 2015-08-15 11:56 UTC
Is it possible to lock the push to the database. Let's create a use case:
- The production server is ready and there is many information about the page and some blog posts
- I am doing something on my local machine
- Let's push to git
- I accidentially push with `wordmove push --all`
- Now, where do I get my data back? So I need the option to lock the pushing

**Comment by pioneerskies** [comment] 2015-08-28 08:16
Hm...I understand your fear :)

Wordmove will always save a dump of the remote database inside the `wp-content/` folder anyway, so if you'll blank the remote db my mistake, you'll have the dump to restore manually.

A really raw way to lock the push is to comment out the database section inside the `Movefile`.

Could these informations helps?

**Comment by essenmitsosse** [comment] 2015-08-28 09:30
Would be nice as a feature. To be able to something to the wordmove file like block push/pull of database/template/uploads etc.

    block-push:
        -database: true

Because: I might get a database back-up, but what if I overwrite the uploads folder? Of course I should always have a proper backup, but at least this would save the work of restoring from the backup, including the downtime caused by this.

**Comment by pioneerskies** [comment] 2015-08-28 09:38
My fear is that than WordMove would require an alarm to remember us to add the lock option!
Out of jokes ;) I'm tagging as a feature request and we'll elaborate a bit on this.

My bigger concern is to try to avoid an excessive grow of the Movefile, but the feature should be achieved by other ways.

Thanks for your interventions

**Comment by iDuuck** [comment] 2015-08-28 09:41
It's just growing, if needed. And I would rather have a bigger Movefile
than a broken service.

**Comment by pioneerskies** [comment] 2018-04-06 14:39
Closed by #447 🎉

**Closed by pioneerskies** 2018-04-06 14:39 UTC
Labels: feature, push
