### ISSUE TITLE
553 Can't open that file: No such file or directory (Net::FTPPermError)

### ISSUE THREAD

**Issue by erezLieberman** [welaika/wordmove#285] opened 2016-02-24 12:05 UTC
git this error:

```
 remote | write http://174.137.191.60/~amosboaz/wp-content/dump.php
/usr/lib/ruby/2.1.0/net/ftp.rb:327:in `getresp': 553 Can't open that file: No such file or directory (Net::FTPPermError)
	from /usr/lib/ruby/2.1.0/net/ftp.rb:352:in `block in sendcmd'
	from /usr/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
	from /usr/lib/ruby/2.1.0/net/ftp.rb:350:in `sendcmd'
	from /usr/lib/ruby/2.1.0/net/ftp.rb:430:in `transfercmd'
	from /usr/lib/ruby/2.1.0/net/ftp.rb:547:in `block (2 levels) in storbinary'
	from /usr/lib/ruby/2.1.0/net/ftp.rb:199:in `with_binary'
	from /usr/lib/ruby/2.1.0/net/ftp.rb:546:in `block in storbinary'
	from /usr/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
	from /usr/lib/ruby/2.1.0/net/ftp.rb:545:in `storbinary'
	from /usr/lib/ruby/2.1.0/net/ftp.rb:694:in `putbinaryfile'
	from /usr/lib/ruby/2.1.0/net/ftp.rb:722:in `put'
	from /var/lib/gems/2.1.0/gems/photocopier-1.0.0/lib/photocopier/ftp.rb:17:in `put_file'
	from /var/lib/gems/2.1.0/gems/photocopier-1.0.0/lib/photocopier/adapter.rb:12:in `put'
	from /var/lib/gems/2.1.0/gems/wordmove-1.3.1/lib/wordmove/deployer/ftp.rb:69:in `remote_put'
	from /var/lib/gems/2.1.0/gems/wordmove-1.3.1/lib/wordmove/deployer/ftp.rb:98:in `download_remote_db'
	from /var/lib/gems/2.1.0/gems/wordmove-1.3.1/lib/wordmove/deployer/ftp.rb:18:in `push_db'
	from /var/lib/gems/2.1.0/gems/wordmove-1.3.1/lib/wordmove/cli.rb:60:in `block in push'
	from /var/lib/gems/2.1.0/gems/wordmove-1.3.1/lib/wordmove/cli.rb:36:in `block in handle_options'
	from /var/lib/gems/2.1.0/gems/wordmove-1.3.1/lib/wordmove/cli.rb:34:in `each'
	from /var/lib/gems/2.1.0/gems/wordmove-1.3.1/lib/wordmove/cli.rb:34:in `handle_options'
	from /var/lib/gems/2.1.0/gems/wordmove-1.3.1/lib/wordmove/cli.rb:59:in `push'
	from /var/lib/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /var/lib/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /var/lib/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /var/lib/gems/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /var/lib/gems/2.1.0/gems/wordmove-1.3.1/exe/wordmove:6:in `<top (required)>'
	from /usr/local/bin/wordmove:22:in `load'
	from /usr/local/bin/wordmove:22:in `<main>'
```

i looked on this links:
https://github.com/welaika/wordmove/issues/192
https://github.com/welaika/wordmove/issues/134

but didnt help :(

**Comment by pioneerskies** [comment] 2016-02-27 09:24
Hi! Could I ask you to take the time to lift a bit the issue following [these tips](https://github.com/welaika/wordmove/wiki/Contributor-Guide#bug-reporting)?

Thanks in advance

**Comment by pioneerskies** [comment] 2016-02-27 09:36
Photocopier recently received a PR about file permissions using FTP (https://github.com/welaika/photocopier/pull/16).

The changes will be ready to use in Wordmove 2.0 - it should have been published yesterday, but...it ins't yet - or in the preview version

    gem uninstall wordmove
    gem install wordmove --pre

Do you have the time to try if your problem is related to that PR?

**Comment by mukkoo** [comment] 2016-04-11 16:20
@erezLieberman can you try with wordmove 2.0?

**Comment by erezLieberman** [comment] 2016-04-12 09:03
no change :( like before...

remote | write http://174.137.191.60/~amosboaz/wp-content/dump.php
/usr/lib/ruby/2.1.0/net/ftp.rb:327:in `getresp': 553 Can't open that file: No such file or directory (Net::FTPPermError)
        from /usr/lib/ruby/2.1.0/net/ftp.rb:352:in `block in sendcmd'
        from /usr/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
        from /usr/lib/ruby/2.1.0/net/ftp.rb:350:in `sendcmd'
        from /usr/lib/ruby/2.1.0/net/ftp.rb:430:in `transfercmd'
        from /usr/lib/ruby/2.1.0/net/ftp.rb:547:in `block (2 levels) in storbinary'
        from /usr/lib/ruby/2.1.0/net/ftp.rb:199:in `with_binary'
        from /usr/lib/ruby/2.1.0/net/ftp.rb:546:in `block in storbinary'
        from /usr/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
        from /usr/lib/ruby/2.1.0/net/ftp.rb:545:in `storbinary'
        from /usr/lib/ruby/2.1.0/net/ftp.rb:694:in `putbinaryfile'
        from /usr/lib/ruby/2.1.0/net/ftp.rb:722:in `put'
        from /var/lib/gems/2.1.0/gems/photocopier-1.1.1/lib/photocopier/ftp.rb:16:in `put_file'
        from /var/lib/gems/2.1.0/gems/photocopier-1.1.1/lib/photocopier/adapter.rb:12:in `put'
        from /var/lib/gems/2.1.0/gems/wordmove-2.0.0/lib/wordmove/deployer/ftp.rb:69:in `remote_put'
        from /var/lib/gems/2.1.0/gems/wordmove-2.0.0/lib/wordmove/deployer/ftp.rb:97:in `download_remote_db'
        from /var/lib/gems/2.1.0/gems/wordmove-2.0.0/lib/wordmove/deployer/ftp.rb:17:in `push_db'
        from /var/lib/gems/2.1.0/gems/wordmove-2.0.0/lib/wordmove/cli.rb:86:in `block in push'
        from /var/lib/gems/2.1.0/gems/wordmove-2.0.0/lib/wordmove/cli.rb:37:in `block in handle_options'
        from /var/lib/gems/2.1.0/gems/wordmove-2.0.0/lib/wordmove/cli.rb:36:in `each'
        from /var/lib/gems/2.1.0/gems/wordmove-2.0.0/lib/wordmove/cli.rb:36:in `handle_options'
        from /var/lib/gems/2.1.0/gems/wordmove-2.0.0/lib/wordmove/cli.rb:85:in `push'
        from /var/lib/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /var/lib/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /var/lib/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from /var/lib/gems/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /var/lib/gems/2.1.0/gems/wordmove-2.0.0/exe/wordmove:6:in `<top (required)>'
        from /usr/local/bin/wordmove:22:in `load'
        from /usr/local/bin/wordmove:22:in `<main>'

**Comment by pioneerskies** [comment] 2016-05-24 07:23
I really have to ask you to take the time to lift a bit the issue following [these tips](https://github.com/welaika/wordmove/wiki/Contributor-Guide#bug-reporting)

Thanks in advance

**Comment by yousan** [comment] 2016-07-19 23:23
I got same error.
```
$  wordmove pull -d

▬▬ ✓ Using Movefile: ./Movefile ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬

▬▬ ✓ Pulling Database ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
    local | mysqldump --host=127.0.0.1 --user=yousan --password=password--result-file="/Users/yousan/public_html/example.com/wp-content/local-backup-1468970075.sql" yousan_example
mysqldump: [Warning] Using a password on the command line interface can be insecure.
   remote | write /home/user/www/example.com/wp-content/dump.php
/usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/net/ftp.rb:342:in `getresp': 550 /home/user/www/example.com/wp-content/dump.php: No such file or directory (Net::FTPPermError)
```

- local
 Mac OS X 10.11.5 (Darwin aramaki.local 15.5.0)
 ruby -v ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
 wordmove -v 2.0.0
- remote
 FreeBSD 9.1-RELEASE-p24
 ProFTPD 1.3.5a
 OpenSSH_6.9p1, LibreSSL 2.1.8

**Comment by pioneerskies** [comment] 2016-07-25 14:20
That really means `/home/user/www/example.com/wp-content/dump.php` is not there as far as I can see. Can you check if the file is left on the server and what permissions it has?

The overall process is working fine in what we consider a standard environment (getting it work in the "real life" here), so we have to understand what is specifically going wrong on your env, or we can't have a clue.

**Comment by yousan** [comment] 2016-07-26 00:44
`dump.php` is not created.
The permission of `wp-content` looks 755
```
$ ls -lat /home/user/www/example.com/wp-content/dump.php
ls: /home/user/www/example.com/wp-content/dump.php: No such file or directory
$ ls -latd .
drwxr-xr-x   5 yousan  users   1024 Jul 18 23:44 .
``

**Comment by pioneerskies** [comment] 2016-07-27 09:17
@yousan , could you please attach your `Movefile` - wiped from users/passwords?

Overall I'd like to see if you're using `wordpress_absolute_path`...

**Comment by brunoDegaspare** [comment] 2016-10-06 11:12
I apologise in advance if I am posting on the wrong place but I am getting the same 553 error related to this `dump.php` file.

Here is how I configured my Movefile (I omitted user and password details):

`
local:
  vhost: "http://localhost:8888/mysite"
  wordpress_path: "/Users/bruno/Documents/01_Projects/Sites/mysite" # use an absolute path here

  database:
    name: "myuser"
    user: "root"
    password: "root"
    host: "localhost"

production:
  vhost: "http://www.mysite.com"
  wordpress_path: "/home/mysite/public_html" # use an absolute path here

  database:
    name: "mydb"
    user: "myuser"
    password: "password"
    host: "host"
    # port: "3308" # Use just in case you have exotic server config
    # mysqldump_options: "--max_allowed_packet=1G" # Only available if using SSH

  exclude:
    - ".git/"
    - ".gitignore"
    - ".sass-cache/"
    - "node_modules/"
    - "bin/"
    - "tmp/*"
    - "Gemfile*"
    - "Movefile"
    - "wp-config.php"
    - "wp-content/*.sql"

  # paths: # you can customize wordpress internal paths
  #   wp_content: "wp-content"
  #   uploads: "wp-content/uploads"
  #   plugins: "wp-content/plugins"
  #   mu_plugins: "wp-content/mu-plugins"
  #   themes: "wp-content/themes"
  #   languages: "wp-content/languages"

  # ssh:
  #   host: "host"
  #   user: "user"
  #   password: "password" # password is optional, will use public keys if available.
  #   port: 22 # Port is optional
  #   rsync_options: "--verbose" # Additional rsync options, optional
  #   gateway: # Gateway is optional
  #     host: "host"
  #     user: "user"
  #     password: "password" # password is optional, will use public keys if available.

  ftp:
    user: "myftpuser"
    password: "password"
    host: "ftp.mysite.com"
    passive: true
    scheme: "ftp" # default "ftp"

# staging: # multiple environments can be specified
#   [...]
`

I have already tried `passive: false` but still get the same error. Not sure what's the solution for this.

**Comment by brunoDegaspare** [comment] 2016-10-08 13:42
After following the instructions to install lftp here [https://github.com/welaika/wordmove/wiki/Install-lftp-on-OSX-yosemite](url) it finally worked.

**Comment by pioneerskies** [comment] 2016-10-10 08:01
Thanks @brunoDegaspare for reporting.

In the mean time I'm going to close this issue since it seems abandoned to me.

**Closed by pioneerskies** 2016-10-10 08:01 UTC
Labels: FTP, help

**Comment by JoseVitor20** [comment] 2025-03-22 13:31
The error happens because you are failing to send important files or directories for shipping on deploy. 

Try to remove each directories or files listed in the 'exclusion' until you find the error.

Example of the wrong passage ❌:
--------------------------
exclude:
    - ".git/"
    - ".gitignore"
    - ".sass-cache/"
    - "node_modules/"
    - "bin/"
    - "tmp/*"
    - "Gemfile*"
    - "Movefile"
    - "wp-config.php"
    - "wp-content/*.sql"
--------------------------

Take the tests 🧪:   
--------------------------
exclude:
    - ".git/"
    - ".gitignore"
    - ".sass-cache/"
    - "node_modules/"
    - "bin/"
    # Remove one by one until you find the directory that is causing the problem
--------------------------

**Comment by JoseVitor20** [comment] 2025-03-22 13:49
# The error happens because you are failing to send important files or directories in shipping to deploy. 

 # Try to remove each of the directories or files that are listed in the 'exclusion' until you find the error. 

 ## Example of the wrong passage ❌:
```yml
exclude:
    - ".git/"
    - ".gitignore"
    - ".sass-cache/"
    - "node_modules/"
    - "bin/"
    - "tmp/*"
    - "Gemfile*"
    - "Movefile"
    - "wp-config.php"
    - "wp-content/*.sql"
```

## Do the tests 🧪: 
```yml
exclude:
    - ".git/"
    - ".gitignore"
    - ".sass-cache/"
    - "node_modules/"
    - "bin/"
    - "tmp/*"
    # Remove one by one until you find the directory or file that is causing the problem
```

### In my case, the problem was as you remove from shipping to deploy the directories and files that are listed in these example below:
```yml
exclude: |
 **/.git* # should not be sent to the server for deploy
 **/.env* # should not be sent to the server for deploy
 **/node_modules/* # It should not be sent to the server, must be installed on the server through the 'workflow '
 **/vendor/* # It should not be sent to the server, must be installed on the server through the 'workflow '
 
 **/tests/* # must be sent to the deploy server
 **/database/* # must be sent to the deploy server
 **/storage/* # must be sent to the deploy server
 vendor/** # must be sent to the deploy server
 **/bootstrap/cache/*.php # must be sent to the deploy server
 **/bootstrap/cache/*.json # must be sent to the deploy server
 **/bootstrap/cache/*.config.php # must be sent to the deploy server
```

**Comment by JoseVitor20** [comment] 2025-03-22 14:01
# The error occurs because you are not sending the necessary files or directories for your project on the server.

# Try removing each of the directories or files listed in the 'exclude' section until you find the error.

## Example of the wrong configuration ❌:
```yml
exclude:
    - ".git/"
    - ".gitignore"
    - ".sass-cache/"
    - "node_modules/"
    - "bin/"
    - "tmp/*"
    - "Gemfile*"
    - "Movefile"
    - "wp-config.php"
    - "wp-content/*.sql"
```

## Perform the tests 🧪:
```yml
exclude:
    - ".git/"
    - ".gitignore"
    - ".sass-cache/"
    - "node_modules/"
    - "bin/"
    - "tmp/*"
    # Remove one by one until you find the directory or file causing the issue
```

#### In my case, the problem was caused by not sending the necessary directories or files for the project to function properly. As a result, Git was unable to store files in their respective directories, since these directories were not sent:
```yml
exclude: |
 **/.git* # Should not be sent to the server
 **/.env* # Should not be sent to the server
 **/node_modules/* # Should not be sent to the server, it should be installed on the server via 'workflow'
 **/vendor/* # Should not be sent to the server, it should be installed on the server via 'workflow'
 
 **/tests/* # Should be sent to the server
 **/database/* # Should be sent to the server
 **/storage/* # Should be sent to the server
 vendor/** # Should be sent to the server
 **/bootstrap/cache/*.php # Should be sent to the server
 **/bootstrap/cache/*.json # Should be sent to the server
 **/bootstrap/cache/*.config.php # Should be sent to the server
```
