### ISSUE TITLE
Cannot Pull Uploads

### ISSUE THREAD

**Issue by sbehnfeldt** [welaika/wordmove#384] opened 2017-04-08 12:59 UTC
I can pull my database from my staging site to my local site:
wordmove pull -d -e staging

But I can't pull my uploads:
wordmove pull -u -e staging

Amongst the output I see, "The source and destination cannot both be remote."

I do notice that the rsync command line includes a colon in front of the staging site's path:
:/home/username/web/staging/public/wp-content/uploads
even though in my wordmove file the wordpress_path for my staging site does not include this.  I tried executing the rsync manually from my local Windows command prompt and got the same error, but when I removed the colon I got a login prompt.  (Login failed, presumably for other reasons.)

Wordmove 2.0.0 on Windows 10 local, Linux remote

**Comment by pioneerskies** [comment] 2017-05-17 07:37
Could you post your Movefile, please?

**Comment by sbehnfeldt** [comment] 2017-05-18 21:22
[Movefile-Redacted.txt](https://github.com/welaika/wordmove/files/1012473/Movefile-Redacted.txt)

**Comment by sbehnfeldt** [comment] 2017-06-10 12:46
Any progress on this?

**Comment by pioneerskies** [comment] 2017-06-11 10:05
The only thing I could do is to ask you if you have tried with the latest Wordmove version: we have fixed some bugs here and there and moreover we have changed a bit inside a dependency https://github.com/welaika/photocopier/commit/ae80a921ba8e8822e3cc67cac3dd965f3c24cb2f which should be on the path on your problem.

That said: I can't test on Windows and I can't reproduce. It'd be beautiful if some Windows users from the community could take a little ride on this...

**Comment by truwo** [comment] 2017-09-10 09:51
I'm experiencing the very same using wordmove 2.1.3 inside vagrant vm using Ubuntu 14.04.5. My machine is running OSX. The very same happens not only for uploads, but for all pulls of file related stuff, where rsync cammand is issued similarly with different paths. The colon is only put to the front of the source path, not to the formt of the target path of rsync.

This is the rsync command that fails (here for themes):
rsync --progress -e 'sshpass -p vagrant ssh vagrant@wz.dev' -rlpt --compress --omit-dir-times --delete --exclude .git/ --exclude .gitignore --exclude .sass-cache/ --exclude node_modules/ --exclude bin/ --exclude tmp/\* --exclude Gemfile\* --exclude Movefile --exclude wp-config.php --exclude wp-content/\*.sql :/srv/www/wz-dev/htdocs/wp-content/themes/ /srv/www/local-dev/htdocs/wp-content/themes

**Comment by pioneerskies** [comment] 2018-04-16 10:13
@truwo Wordmove **always** consider one stage the local one and the other a remote one.

You can't work outside of the vagrant box with wordmove and perform a pull/push operation across to "remote" machines.

The colon is put where wordmove considers the stage to be remote. Open an ad hoc issue if you need.

Going to close this one because abandoned.

Cheers

**Closed by pioneerskies** 2018-04-16 10:13 UTC
Labels: SSH, cannot_reproduce, pull, windows
