### ISSUE TITLE
Error on pull: Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated.

### ISSUE THREAD

**Issue by tomhayes** [welaika/wordmove#649] opened 2022-03-03 18:10 UTC
**Describe the bug**

I'm getting the following error when trying to `wordmove pull -e production -tdup`:

```
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
/Users/tom/.rubies/ruby-3.1.1/lib/ruby/3.1.0/psych.rb:323:in `safe_load': wrong number of arguments (given 4, expected 1) (ArgumentError)
```

**Wordmove command**

`wordmove pull -e production -tdup`:

**Expected behavior**

Pulls DB, theme, uploads and plugins

**movefile.yml**

> Paste (removing personal data) the interesting part, if any, of your `movefile.yml` formatting it inside a code block with `yml` syntax and double checking the indentation.

**Exception/trace**

```
        from /Users/tom/.gem/ruby/3.1.1/gems/wordmove-5.2.2/lib/wordmove/movefile.rb:30:in `fetch'
        from /Users/tom/.gem/ruby/3.1.1/gems/wordmove-5.2.2/lib/wordmove/movefile.rb:46:in `environment'
        from /Users/tom/.gem/ruby/3.1.1/gems/wordmove-5.2.2/lib/wordmove/movefile.rb:34:in `load_dotenv'
        from /Users/tom/.gem/ruby/3.1.1/gems/wordmove-5.2.2/lib/wordmove/deployer/base.rb:11:in `deployer_for'
        from /Users/tom/.gem/ruby/3.1.1/gems/wordmove-5.2.2/lib/wordmove/cli.rb:81:in `pull'
        from /Users/tom/.gem/ruby/3.1.1/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
        from /Users/tom/.gem/ruby/3.1.1/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
        from /Users/tom/.gem/ruby/3.1.1/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
        from /Users/tom/.gem/ruby/3.1.1/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
        from /Users/tom/.gem/ruby/3.1.1/gems/wordmove-5.2.2/exe/wordmove:6:in `<top (required)>'
        from /Users/tom/.gem/ruby/3.1.1/bin/wordmove:25:in `load'
        from /Users/tom/.gem/ruby/3.1.1/bin/wordmove:25:in `<main>'
```

**Environment (please complete the following information):**

- OS: MacOS Monterey
- Ruby: (`ruby --version`) 3.1.1p18
- Wordmove: (`wordmove --version`) 
`wordmove --version` doesn't work, gives me the error `Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
5.2.2`

**Doctor**

* [] running the `wordmove doctor` command returns all green

> (If it is not, report the error you got.)

```
/Users/tom/.rubies/ruby-3.1.1/lib/ruby/3.1.0/psych.rb:323:in `safe_load': wrong number of arguments (given 4, expected 1) (ArgumentError)
        from /Users/tom/.gem/ruby/3.1.1/gems/wordmove-5.2.2/lib/wordmove/movefile.rb:30:in `fetch'
        from /Users/tom/.gem/ruby/3.1.1/gems/wordmove-5.2.2/lib/wordmove/doctor/movefile.rb:11:in `initialize'
        from /Users/tom/.gem/ruby/3.1.1/gems/wordmove-5.2.2/lib/wordmove/doctor.rb:13:in `new'
        from /Users/tom/.gem/ruby/3.1.1/gems/wordmove-5.2.2/lib/wordmove/doctor.rb:13:in `movefile'
        from /Users/tom/.gem/ruby/3.1.1/gems/wordmove-5.2.2/lib/wordmove/doctor.rb:5:in `start'
        from /Users/tom/.gem/ruby/3.1.1/gems/wordmove-5.2.2/lib/wordmove/cli.rb:17:in `doctor'
        from /Users/tom/.gem/ruby/3.1.1/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
        from /Users/tom/.gem/ruby/3.1.1/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
        from /Users/tom/.gem/ruby/3.1.1/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
        from /Users/tom/.gem/ruby/3.1.1/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
        from /Users/tom/.gem/ruby/3.1.1/gems/wordmove-5.2.2/exe/wordmove:6:in `<top (required)>'
        from /Users/tom/.gem/ruby/3.1.1/bin/wordmove:25:in `load'
        from /Users/tom/.gem/ruby/3.1.1/bin/wordmove:25:in `<main>'
```

**Comment by pioneerskies** [comment] 2022-03-05 17:50
@tomhayes this is totally my fault: being working on the new version for more than a year now and I've not correctly maintained the 5.x branch.

The problem is that 5.x isn't compatible with ruby 3.x. This should be declared into the software, in order to give an explicit error to the user at installation time.

Latest 2.x (2.7.5 AFAIK) ruby version should enable you to use wordmove's stable version.

Let me know if it helps.

**Comment by kaktux** [comment] 2022-05-18 10:37
> 
> The problem is that 5.x isn't compatible with ruby 3.x. This should be declared into the software, in order to give an explicit error to the user at installation time.
> 
> Latest 2.x (2.7.5 AFAIK) ruby version should enable you to use wordmove's stable version.
> 

I just [asked a question about an error i have with a new installation](https://github.com/welaika/wordmove/discussions/653) (that came with ruby 3.x) that may be (?) caused by the same in the discussions. Could my problem be related?

**Comment by alessandro-fazzi** [comment] 2022-05-18 18:09
I'm quite sure. I've replied there (reading notifications in order ^^")

Maybe, if you could confirm, I could close this issue too. :)

**Closed** 2022-09-21 03:10 UTC
Labels: status:wontfix
