### ISSUE TITLE
WORDMOVE installation error console Ubuntu de Windows

### ISSUE THREAD

**Issue by FlorentinaArandano** [welaika/wordmove#342] opened 2016-09-19 21:25 UTC
After installing successfully gem
Attached error:
![error](https://cloud.githubusercontent.com/assets/18351194/18649535/5fe64ac2-7e96-11e6-9602-aac7732079de.JPG)

**Comment by kLOsk** [comment] 2016-10-02 05:32
This sounds more like a Ruby Installation issue.

Have a look at this: http://stackoverflow.com/questions/18908708/installing-ruby-gem-in-windows

**Comment by pioneerskies** [comment] 2016-10-02 07:59
@FlorentinaArandano I can confirm there's not yet snothing to do with Wordmove there. The problem is with your ruby installation.

And as far as some of us here are ruby-ists, we can't afford to help you on a windows system.

I have this clue from a past discussion https://github.com/welaika/wordmove/issues/252#issuecomment-209778746; but I have no competence at all about it. I'm sorry.

As a final note:

    spec.required_ruby_version = "~> 2.0"

which means we do not support ruby versions prior to 2.0 and you are trying on your system with the - quite old! - 1.9.1.

Cheers

**Comment by phidomo** [comment] 2016-12-01 04:12
To get Wordmove installed with Windows bash I had to do the steps below:

sudo apt-get install rubygems-integration
sudo apt-get install ruby-dev

sudo apt-add-repository ppa:brightbox/ruby-ng
sudo apt-get update
sudo apt-get install ruby2.3

sudo apt-get install build-essential
gem install wordmove

Now I have Wordmove installed but still have problems when trying to push/pull.

**Comment by kLOsk** [comment] 2016-12-08 03:45
@phidomo what's the issue?

**Comment by phidomo** [comment] 2016-12-10 07:53
@kLOsk I can transfer files with wordmove but having trouble with the database. First it couldn't connect with MySql but I can solve that with
https://github.com/Microsoft/BashOnWindows/issues/745
sudo /etc/init.d/mysql start

But now I get a mysqldump error: "Access denied for user". I'm using VVV so I guess it is the same problem as in https://github.com/welaika/wordmove/issues/98. So I should install wordmove in Vagrant.

**Comment by pioneerskies** [comment] 2016-12-10 09:53
@phidomo during mysql operations Wordmove should print on the STDOUT what command it is running. That is the raw underneath command. I suggest you to copy that one and ensuring it could be run correctly on you dev environment before to proceed.

Take also a look in the wiki about some tips on using Wordmove with VVV and feel free to contribute there if it is needed :)

**Comment by kLOsk** [comment] 2016-12-11 04:24
Also, this sounds like a non-wordmove issue :) Have you tried using WAMP or MAMP for Windows instead of VVV? Might make things easier for starting out!

**Comment by phidomo** [comment] 2016-12-11 05:31
I installed Wordmove inside of VVV. It was an easier solution to just use the Vagrant VM than to try to make Wordmove work with bash and VVV.

**Comment by pioneerskies** [comment] 2016-12-11 15:24
I work on WP using just `wp server`  from wp-cli ... just saying for inspiration about simplicity :P ;)

**Comment by phidodido** [comment] 2017-03-18 03:39
I got Wordmove working with Windows 10 bash. See this wiki page https://github.com/welaika/wordmove/wiki/How-to-install-Wordmove-on-Windows-10-with-Bash

**Comment by pioneerskies** [comment] 2017-03-18 08:20
@phidodido your contribution is just something **beautiful**

And I am really happy to see that it can work with those few steps. Wonderful. Thank you!

Oh well...I'm also going to close this issue

**Closed by pioneerskies** 2017-03-18 08:20 UTC
Labels: windows
