### ISSUE TITLE
Pull return sh: mysql: command not found

### ISSUE THREAD

**Issue by eamaral92** [welaika/wordmove#330] opened 2016-07-13 13:32 UTC
Hi!

I have a problem when the dump.sql try to up in my local mysql. Wordmove return "command not found" , but my mysql command works normally on terminal!

```
gzip -d --force "/users/macweb02/Documents/projects/apaebarueri/wp-content/dump.sql.gz"
    local | gzip -d --force "/users/macweb02/Documents/projects/apaebarueri/wp-content/dump.sql.gz"
    local | adapt dump
    local | mysql --host=localhost --user=x --password=x --database=x --execute="SET autocommit=0;SOURCE /users/macweb02/Documents/projects/apaebarueri/wp-content/dump.sql;COMMIT"
sh: mysql: command not found
/Users/macweb02/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/wordmove-2.0.0/lib/wordmove/deployer/base.rb:132:in `run': Return code reports an error (Wordmove::ShellCommandError)
```

**Comment by pioneerskies** [comment] 2016-07-14 08:13
Could you please add some information referring to the contributor guide [here](https://github.com/welaika/wordmove/wiki/Contributor-Guide#bug-reporting)?

**Comment by eamaral92** [comment] 2016-07-14 12:37
Sorry!

macOSX 10.11.4 (15E65) El Captain
ruby 2.2.3p173
`local:
  vhost: "http://apaebarueri.dev"
  wordpress_path: "/users/macweb02/Documents/projects/apaebarueri" # use an absolute path here

  database:
    name: "apaebarueri"
    user: "xxx"
    password: "xxx"
    host: "localhost"

staging:
  vhost: "http://previa.adesign.com.br/apaebarueri"
  wordpress_path: "/srv/users/serverpilot/apps/previa/public/apaebarueri" # use an absolute path here

  database:
    name: "apaebarueri"
    user: "xxx"
    password: "xxx"
    host: "localhost"

  exclude:
    - ".git/"
    - ".gitignore"
    - ".sass-cache/"
    - "node_modules/"
    - "bin/"
    - "tmp/*"
    - "Gemfile*"
    - "Movefile"
    - "wp-config.php"
    - "wp-content/*.sql"

  ssh:
    host: "xxx"
    user: "xxx"
  #   password: "password" # password is optional, will use public keys if available.
  #   port: 22 # Port is optional
  #   rsync_options: "--verbose" # Additional rsync options, optional
  #   gateway: # Gateway is optional
  #     host: "host"
  #     user: "user"
  #     password: "password" # password is optional, will use public keys if available.

# production: # multiple environments can be specified
#   [...]
`

**Comment by pioneerskies** [comment] 2016-07-25 14:35
Ok..here we go:

* what's the output of `which mysql`?
* what's your wordmove version? ([this was reported to be an important information](http://cdn2.cagepotato.com/wp-content/uploads/2013/02/i-see-what-you-did-there.jpg))

**Comment by pioneerskies** [comment] 2016-07-25 14:36
Oh! Are you using Vagrant? If it is the case, are you calling wormdove from inside the vagrant box?

**Comment by pioneerskies** [comment] 2017-02-18 16:56
closing due to no interactions

**Closed by pioneerskies** 2017-02-18 16:56 UTC

**Comment by RyanCameronMe** [comment] 2017-04-12 03:57
I'm having a the same error, I can push all files but not the db. I am using mac sierra with vvv. I am getting:
sh: mysqldump: command not found
/usr/local/lib/ruby/gems/2.3.0/gems/wordmove-2.0.0/lib/wordmove/deployer/base.rb:132:in `run': Return code reports an error (Wordmove::ShellCommandError)

**Comment by pioneerskies** [comment] 2017-05-17 07:36
@RyanCameronMe you really need to have `mysqldump` installed and in your $PATH. And if you are inside Vagrant, the same is valid. I bet if you ssh into vagrant and run `which mysqldump` you will get nothing back; and if I'm right the problem is there

**Comment by frontenddevguy** [comment] 2019-11-19 09:38
Where should mysqldump be installed? Both local and live server?

**Comment by pioneerskies** [comment] 2019-11-19 14:58
Yeah @frontenddevguy for sure 😃

We need to dump in anywhere you'd like to deploy or pull the DB :)

We consider that anywhere you have a PHP+MySQL application you'll have also `mysqldump`. If it is a custom server and you have DB on another machine you'll need to install just mysql-client package in order to have the command.

Just keep in mind that following up on such an old and closed issue can't assure  you'll have a reply ;)

**Comment by frontenddevguy** [comment] 2019-11-20 16:52
Thanks for replying and clarifying. It seems I am going down the rabbit hole of making Zsh and Wordmove know where mysqldump is located with a symlink. Assuming once that works Wordmove db push/pull will also!

**Comment by pioneerskies** [comment] 2019-11-20 17:54
Oh! I wish you best luck @frontenddevguy . Unfortunately I'm on fish and my colleagues and remote servers on bash, so I do not have use cases for zsh 😄
