### ISSUE TITLE
403 on dump.php

### ISSUE THREAD

**Issue by blocka** [welaika/wordmove#120] opened 2015-01-17 16:55 UTC
Not sure if this is a host specific issue or not, but I get a 403 on the dump.php file when its in wp-content. If I move it out to the root, it works fine.

**Comment by pioneerskies** [comment] 2015-01-19 10:05
Hi @blocka ,

mmmm...I've just tried locally to `GET` directly a php file inside `wp-content` and it just works.

```bash
✔ ~/dev/prossimita [2.1.5]  (git:master)
↳ $ echo "test" > wp-content/test.php

✔ ~/dev/prossimita [2.1.5]  (git: master )
↳ $ curl http://localhost:8080/wp-content/test.php
test
```

Anyway if it should be an issue specific to your host, I'd call it a security feature, not a bug :)

Moreover, why and how are you moving `dump.php` in another folder? It is an automatically generated file; have you patched Wordmove's code in order to create it in a different position?

**Comment by blocka** [comment] 2015-01-19 10:25
I manually moved it to see what would happen. My host did implement it as a security feature, but in that case, perhaps it should make sense not to put it in wp-content? I'm assuming you did that out of "security through obscurity". Why not put it in the root, or make a random folder (together with a random name) instead?

**Comment by pioneerskies** [comment] 2015-01-19 13:59
If I'd have to give you a fast answer, this design decision was taken because of the exotic setups wordpress is capable of, e.g.: folder, sub-folder, w/ wp-content moved away and even more.

We'll consider your situation and try to analyze your precious suggestions :)

Thanks a lot

**Comment by delphaber** [comment] 2015-09-11 14:35
I'm closing this. PR is welcome :)

**Closed by delphaber** 2015-09-11 14:35 UTC
Labels: feature, help
