### ISSUE TITLE
Wordmove::ShellCommandError

### ISSUE THREAD

**Issue by RaMonkey** [welaika/wordmove#215] opened 2015-09-09 07:07 UTC
```bash
▬▬ ✓ Pushing Database ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
   remote | write /domains/blblabla.com/public_html/test-lab/wp-content/dump.php
    local | download http://blablabla.com/test-lab/wp-content/dump.php?shared_key=95370a688e3320879807a2898c7d7f2feadf78e30e166f6bfa336564689f6ef4964bf19e4ff6edc8 > /Users/ramon/Sites/WP-SITES/test-lab/wp-content/remote-backup-1441782106.sql
   remote | delete: /domains/blablabla.com/public_html/test-lab/wp-content/dump.php
mysqldump --host=localhost --user=xxxx --password=xxxxxxxx test-lab --result-file=/Users/ramon/Sites/WP-SITES/test-lab/wp-content/dump.sql
    local | mysqldump --host=localhost --user=xxxx --password=xxxxxxxx test-lab --result-file=/Users/ramon/Sites/WP-SITES/test-lab/wp-content/dump.sql
/Library/Ruby/Gems/2.0.0/gems/wordmove-1.3.1/lib/wordmove/deployer/base.rb:136:in `run': Return code reports an error (Wordmove::ShellCommandError)
	from /Library/Ruby/Gems/2.0.0/gems/wordmove-1.3.1/lib/wordmove/deployer/base.rb:208:in `save_local_db'
	from /Library/Ruby/Gems/2.0.0/gems/wordmove-1.3.1/lib/wordmove/deployer/ftp.rb:19:in `push_db'
	from /Library/Ruby/Gems/2.0.0/gems/wordmove-1.3.1/lib/wordmove/cli.rb:60:in `block in push'
	from /Library/Ruby/Gems/2.0.0/gems/wordmove-1.3.1/lib/wordmove/cli.rb:36:in `block in handle_options'
	from /Library/Ruby/Gems/2.0.0/gems/wordmove-1.3.1/lib/wordmove/cli.rb:34:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/wordmove-1.3.1/lib/wordmove/cli.rb:34:in `handle_options'
	from /Library/Ruby/Gems/2.0.0/gems/wordmove-1.3.1/lib/wordmove/cli.rb:59:in `push'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/wordmove-1.3.1/exe/wordmove:6:in `<top (required)>'
	from /usr/bin/wordmove:23:in `load'
	from /usr/bin/wordmove:23:in `<main>'
```

Push/Pull files work fine but can't get the DB Pushed nor Pulled.

Using Mamp locally.

```yml
local: 
  database: 
    host: "localhost"
    name: test-lab
    password: ********
    user: ****
  vhost: "http://localhost:8888/test-lab"
  wordpress_path: /Users/ramon/Sites/WP-SITES/test-lab
production: 
  database: 
    host: localhost
    name: *******-lab
    password: ********
    user: ************
  exclude: 
    - .git/
    - .gitignore
    - .sass-cache/
    - node_modules/
    - bin/
    - tmp/*
    - Gemfile*
    - Movefile
    - wp-config.php
    - wp-content/*.sql
    - scss/
  ftp: 
    host: blablabla.com
    password: ********
    user: ********
  vhost: "http://blablabla.com/test-lab"
  wordpress_path: /domains/blablabla.com/public_html/test-lab
```

**Comment by pioneerskies** [comment] 2015-09-10 09:33
If you execute in your terninal the failing command what does it tells you?

`mysqldump --host=localhost --user=xxxx --password=xxxxxxxx test-lab --result-file=/Users/ramon/Sites/WP-SITES/test-lab/wp-content/dump.sql`

What's you Wordmove version?

**Comment by RamonTonnaer** [comment] 2015-09-10 14:51
Hi Pioneerskies,

After a wordmove push --all, there's a dump.msql in wp-content on live site of 256B with content:

-- Created at 10.9.2015 16:37 using David Grudl MySQL Dump Utility
-- Host: xxxxxxx.com
-- MySQL Server: 5.5.42-MariaDB-cll-lve
-- Database: xxxxxxxx_test-lab

SET NAMES utf8;
SET SQL_MODE='NO_AUTO_VALUE_ON_ZERO';
SET FOREIGN_KEY_CHECKS=0;
-- THE END

wordmove-1.3.1

**Comment by RaMonkey** [comment] 2015-09-10 14:58
Hi Pioneerskies,

After a wordmove push --all, files are being pushed to the server. In wp-content there's a dump.msql of 256 B containing:

-- Created at 10.9.2015 16:37 using David Grudl MySQL Dump Utility
-- Host: name.com
-- MySQL Server: 5.5.42-MariaDB-cll-lve
-- Database: user_test-lab

SET NAMES utf8;
SET SQL_MODE='NO_AUTO_VALUE_ON_ZERO';
SET FOREIGN_KEY_CHECKS=0;
-- THE END

Wordmove version 1.3.1.

**Comment by Jeger** [comment] 2015-09-10 15:44
Hi, i'm having the exact same problem.
The same exact error message, same version of wordmove.

Running the failing command:

    mysqldump --host=localhost --user=root --password=XXXXXX superbra --result file=/Users/halvard/Documents/Mekom/Prosjekter/superbra/wp-content/local-backup-1441899113.sql

Produces the expected result a new 'local-backup-1441899113.sql' file
The file seems ok:

    -- MySQL dump 10.13  Distrib 5.5.42, for osx10.6 (i386)
    --
    -- Host: localhost    Database: superbra
    -- ------------------------------------------------------
    -- Server version	5.5.42
    ...

**Comment by AlexYudaev** [comment] 2015-09-11 12:43
I also have same problem, i think the issue is in windows shell, windows shell doesn't know mysqldump command. 

How i can configure mysql folder directory?

**Comment by Jeger** [comment] 2015-09-11 14:49
@AlexYudaev  no that is not the same problem as then it does not run at all in your terminal.

If you read mine and @RaMonkey comments we actually do get an output from mysqldump.

The fact that mysqldump is not in your PATH is a different problem and you should try to google that as it has nothing to do with this developer.

**Comment by pioneerskies** [comment] 2015-09-15 08:15
@Jeger thanks for your test. Let's try to go a bit deeper:

```bash
mysqldump --host=localhost --user=root --password=XXXXXX superbra --result-file=/Users/halvard/Documents/Mekom/Prosjekter/superbra/wp-content/dump.sql
```

and just after that run

```echo $?```

what's the reported code?

If we won't have a clue this way I'll need to setup a test env, because I can't reproduce the problem on mine. The code is dropping an exception because the exit status of the command isn't `0` ... this is blowing my mind a bit :)

**Comment by Jeger** [comment] 2015-09-15 09:06
Hi

I just managed to solve the problem:

I have MAMP mysql executables added to path using the following method:
    mysql() {
        /Applications/MAMP/Library/bin/mysql "$@"
    }
    export -f mysql
( http://stackoverflow.com/questions/4145667/how-to-override-the-path-of-php-to-use-the-mamp-path )

And added mysqldump the same way.

When i instead added a linked file to path through /usr/local/bin/ the error no longer happens.

**Comment by pioneerskies** [comment] 2015-09-15 16:00
1st of all I'd like to thank you for your feedback.
2nd: could you order a bit the infos? :D

I think you added

```bash
mysql() {
/Applications/MAMP/Library/bin/mysql "$@"
}
```

```bash
mysqldump() {
/Applications/MAMP/Library/bin/mysqldump "$@"
}
```

in your `.bashrc` or equivalent location; is that right?

Anyway, why even before this action you already had `mysqldump` command available? Do you have multiple mysql installations on your system (e.g.: brew and MAMP)?

Could you then elaborate a bit about «When i instead added a linked file to path through /usr/local/bin/ the error no longer happens»

At last: have you ever read [this](https://github.com/welaika/wordmove/wiki/MAMP-tips) before and eventually followed instructions?

Tanks for your collaboration ;)

Cheers

**Comment by Jeger** [comment] 2015-09-16 10:07
Hi

I'm sorry for not making myself more clear.

when first running wordmove I added the following(to .bash_profile), as i did not have it in PATH at all:

    mysqldump() {
        /Applications/MAMP/Library/bin/mysqldump "$@"
   }

This did *not* work.

 When i removed that from .bash_profile and instead did:

    ln /path/to/mysqldump /usr/local/bin

This works now works.

This seems strange since with both options `mysqldump -v` gave the same output:

    mysqldump  Ver 10.13 Distrib 5.5.42, for osx10.6 (i386)

**Comment by pioneerskies** [comment] 2015-09-16 10:44
It'd be nice if you'd try to follow instructions in the wiki I'd linked before, in order to confirm we are giving the community the right path to follow when using MAMP.

And in the end, have you got multiple MySQL installation on your dev machine?

**Comment by overclokk** [comment] 2016-03-05 00:05
Hi,
I have a similar issue with a `wordmove pull -e production -d`
```
▬▬ ✓ Pulling Database ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
mysqldump --host=localhost --user=wp --password=wp testsite --result-file=/vagrant/www/testsite/htdocs/wp-content/local-backup-1457135784.sql
    local | mysqldump --host=localhost --user=wp --password=wp testsite --result-file=/vagrant/www/testsite/htdocs/wp-content/local-backup-1457135784.sql
   remote | write /public_html/wp-content/dump.php
    local | download http://testsite.com/wp-content/dump.php?shared_key=aeab879f93b0515eb83589aed6cbae83ad142b6412c673b28021097734b9227e156c97c468f65887 > /vagrant/www/testsite/htdocs/wp-content/dump.sql
   remote | delete: /public_html/wp-content/dump.php
    local | adapt dump
mysql --host=localhost --user=wp --password=wp --database=testsite --execute=SOURCE\ /vagrant/www/testsite/htdocs/wp-content/dump.sql
    local | mysql --host=localhost --user=wp --password=wp --database=testsite --execute=SOURCE\ /vagrant/www/testsite/htdocs/wp-content/dump.sql
    local | rm /vagrant/www/testsite/htdocs/wp-content/dump.sql
rm: cannot remove ‘/vagrant/www/testsite/htdocs/wp-content/dump.sql’: Text file busy
/usr/local/rvm/gems/ruby-2.2.1/gems/wordmove-1.3.1/lib/wordmove/deployer/base.rb:137:in `run': Return code reports an error (Wordmove::ShellCommandError)
        from /usr/local/rvm/gems/ruby-2.2.1/gems/wordmove-1.3.1/lib/wordmove/deployer/ftp.rb:48:in `pull_db'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/wordmove-1.3.1/lib/wordmove/cli.rb:49:in `block in pull'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/wordmove-1.3.1/lib/wordmove/cli.rb:36:in `block in handle_options'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/wordmove-1.3.1/lib/wordmove/cli.rb:34:in `each'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/wordmove-1.3.1/lib/wordmove/cli.rb:34:in `handle_options'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/wordmove-1.3.1/lib/wordmove/cli.rb:48:in `pull'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/wordmove-1.3.1/exe/wordmove:6:in `<top (required)>'
        from /usr/local/rvm/gems/ruby-2.2.1/bin/wordmove:23:in `load'
        from /usr/local/rvm/gems/ruby-2.2.1/bin/wordmove:23:in `<main>'
        from /usr/local/rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
        from /usr/local/rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'
```
The issue is only with the DB, with the files no problem
I use vvv
wordmove version 1.3.1
I execute `rm /vagrant/www/testsite/htdocs/wp-content/dump.sql` manually and it works

**Comment by pioneerskies** [comment] 2016-03-13 17:53
Hi @overclokk ,

version 1.3.1 + ftp has a known bug. It is solved in the pre-release version. You can try it out installing it with

    gem install wordmove --pre

I'll close this issue because it is too old. Feel free to reopen as you need

**Closed by pioneerskies** 2016-03-13 17:53 UTC
Labels: help

**Comment by overclokk** [comment] 2016-03-16 10:55
I got this error
```shell
vagrant@vvv:~$ sudo gem install wordmove --pre
ERROR:  Error installing wordmove:
        net-ssh requires Ruby version >= 2.0.
```
I tryed `ruby -v`
```shell
ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-linux]
```
where do I make a mistake?

**Comment by pioneerskies** [comment] 2016-03-16 17:57
`sudo`? Why sudo? And anyway what ruby version returns `sudo ruby --version`?

**Comment by overclokk** [comment] 2016-03-16 18:26
Becasue I got this

```shell
vagrant@vvv:~$ gem install wordmove --pre
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /usr/local/rvm/gems/ruby-2.2.1 directory.
```

but with `sudo ruby --version` I got 1.9 and not 2.2 with `ruby -v`, maybe the problem was rvm
After that I installed ruby 2.2 following that link https://www.brightbox.com/blog/2015/01/05/ruby-2-2-0-packages-for-ubuntu/ and then `gem install wordmove --pre` installed correctly wordmove.
Now I have to tray again to pull and push.
Thank you for now

**Comment by pioneerskies** [comment] 2016-03-17 08:54
kk. We'll wait for your news.
